DROP DATABASE IF EXISTS hex;

CREATE DATABASE hex;

USE hex;

CREATE TABLE users (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(10) UNIQUE,
	wins INTEGER NOT NULL
);

CREATE TABLE savedgames (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	playerone VARCHAR(25),
	playertwo VARCHAR(25),
	gamename VARCHAR(25),
	gamestate VARCHAR(30),
	savedate VARCHAR(30)
);